import { Platform } from 'react-native';
import { name as appName } from '../../app.json';

const isAndroid = Platform.OS === 'android';

const strings = {
  appName,
  account: 'Account',
  activate: 'Activate',
  activatePhysicalCard: 'Activate Card',
  //activatePhysicalCardDesc: 'We have sent an activation code',
  activatePhysicalCardDesc: 'Enter the 6-digit OTP code sent to',
  activationFailed: 'Activation Failed',
  addCard: 'Add Card',
  addReceipt: 'Add Receipt',
  amount: 'Amount',
  approve: 'Approve',
  approver: 'Approver',
  approvers: 'Approvers',
  address: 'Address',
  addAnotherCard: 'Add another card',
  addCategory: 'Add category...',
  addNotes: 'Add notes...',
  addProject: 'Add project...',
  addRule: 'Add rule',
  addressLine1: 'Line 1',
  addressLine2: 'Line 2',
  apply: 'Apply',
  availableBalance: 'Available Balance',
  availableFunds: 'Available funds',

  addOrReferenceNoLabel: 'OR NO / REFERENCE NO',
  addOrReferenceNo: 'Add OR number...',
  addTinNumber: 'Add TIN number...',
  addAddress: 'Add address...',
  addTaxable: 'Add taxable amount',
  addTax: 'Add TAX amount',

  allFieldsAreRequired: 'All Fields are required',
  allow: 'Allow',

  backOfId: 'Back of ID',
  balanceOnCard: 'Balance on card',
  biometricsTitle: 'Use biometrics to access',
  biometricsDesc:
    "To make your life easy, you can use your device's biometrics scanner for fast login and actions that needs confirmation.",

  birthday: 'Birthday',

  cardAdded: 'Card Added',
  cardAddedDesc:
    'You have successfully paired your Xpensio card with your app.',

  cardRequested: 'Card requested',
  cardRequests: 'Card requests',
  cardRequestsDesc:
    'When a member of your team requests for a virtual or plastic card.',

  cancel: 'Cancel',
  category: 'Category',
  continue: 'Continue',
  country: 'Country',
  city: 'City',
  close: 'Close',
  change: 'Change',
  changePin: 'Change PIN',
  changePassword: 'Change password',
  codeOtpSent: 'OTP code sent',
  company: 'Company',
  confirm: 'Confirm',
  confirmAction: 'Confirm action',
  confirmActionDesc:
    'A message  with a verification code will be sent to your phone. Enter the code to continue.',
  confirmWithPassword: 'Confirm this action by entering your password.',
  confirmPinDesc: 'Enter your 4-digit PIN again',
  conversation: 'Conversation',
  currentPassword: 'Current password',
  cvv: 'CVV/CVC',

  dash: '-',
  dateRequested: 'Date Requested',
  dateOfExpiry: 'Date of expiry',
  defaultDate: '01/01/2000',
  deleteReceipt: 'Delete receipt',
  description: 'Description',
  deny: 'Deny',
  denyReason: 'Deny Reason',
  denyReasonCaption: 'Write a reason why this request will be denied?',
  denyPlaceholder: 'Write your reason here',
  details: 'Details',
  disableCard: 'Disable card',
  disapprovePayment: 'Disapprove payment',
  disapprovePaymentDesc: 'Write a reason why this payment is not valid?',
  done: 'Done',

  disable: 'Disable',

  earlier: 'Earlier',
  edit: 'Edit',
  editProfile: 'Edit profile',
  editRule: 'Edit Rule',
  email: 'Email address',
  emptyVirtualCardDesc: 'Best used for online transactions and subscriptions.',
  enable: 'Enable',
  enableCard: 'Enable card',
  enterPassword: 'Enter Password',
  enterPin: 'Enter PIN',
  executives: 'Executives',

  female: 'Female',
  filterBy: 'Filter by',
  fingerprintActivation: 'Fingerprint activation',
  firstName: 'First name',
  forgotPassword: 'Forgot password?',
  forgotYourPassword: 'Forgot your password?',
  forgotYourPasswordDesc:
    'Enter your email address to reset your password. You may need to check your spam folder or unblock no-reply@xpens.io',
  from: 'From',
  frontOfId: 'Front of ID',

  gender: 'Gender',
  getVirtualCard: 'Get virtual card',
  getCard: 'Get Card',
  getCode: 'Get Code',

  hasReceipts: 'Has receipts',
  help: 'Help',

  idType: 'ID type',
  idNumber: 'ID number',
  identification: 'Identification',
  invalidQr: 'Invalid QR',
  invalidQrDesc: 'The scanned QR code is invalid or incorrect',
  issuePlasticCard: 'Issue plastic card',
  issueVirtualCard: 'Issue virtual card',

  lastName: 'Last name',

  limitPerPayment: 'Limit Per Payment',
  limits: 'Limits',
  limitsDesc: 'When you reached 50%, 75%, 90% and max of your purchase limit.',

  lock: 'Lock',
  loggedOut: 'Logged out',
  loggedOutReason: 'For your security, we logged you out. Please log in again.',

  male: 'Male',
  manager: 'Manager',
  marketing: 'Marketing',
  members: 'Members',
  memberRequestedPlasticCard: 'Member requested a plastic card.',
  memberRequestedVirtualCard: 'Member requested a virtual card.',
  merchant: 'Merchant',
  middleName: 'Middle name',
  missingReceipt: 'Missing receipt',
  mobileNumber: 'Mobile Number',
  monthlyLimit: 'Monthly limit',
  myPayments: 'My payments',
  myCards: 'My cards',
  myRequests: 'My requests',

  newPassword: 'New password',
  next: 'Next',
  no: 'No',
  name: 'Name',
  nationality: 'Nationality',
  noAccount: 'No account?',
  noPhotos: 'No Photos',
  noPayments: 'No Payments',
  noNotifications: 'No Notifications',
  noRequests: 'No Requests',
  noTeams: 'No Teams',

  notes: 'Notes',

  notifications: 'Notifications',

  noInternetConnection: 'No Network Connection',

  onPurchases: 'On purchases',
  onPurchasesDesc:
    'When your card is used for any online and in-store purchases.',
  ok: 'Ok',
  or: 'or',
  orNumLabel: 'OR no. / Reference no.',
  originalAmount: 'Original amount',

  openScanner: 'Open scanner',

  paidWith: 'Paid with',
  pairCard: 'Pair card',
  pairRequest: 'Pair a request',
  password: 'Password',
  payments: 'Payments',
  paymentUnavailable: 'Payment Unavailable',
  paymentMethod: 'Payment method',
  perPurchaseLimit: 'Per purchase limit',
  position: 'Position',
  project: 'Project',
  purchaseType: 'Purchase Type',
  purchaseLimits: 'Purchase limits',

  reason: 'Reason',
  reasonHint: 'Write your reason here',
  receipt: 'Receipt',
  receiptDetails: 'Receipt Details',
  request: 'Request',
  requestUnavailable: 'Request Unavailable',
  requestHasBeenApproved: 'Request has been approved',
  requestHasBeenDenied: 'Request has been denied',
  retypePassword: 'Re-type new password',

  personalDetails: 'Personal details',
  pinPlaceholder: '123456',
  pleaseFillUpAllFields: 'Please fill up all fields',

  profile: 'Profile',
  profileChangePinDesc: 'Enter your current PIN',
  profileConfirmPinDesc: 'Enter your new PIN',
  profileVerification: 'Profile verification',
  plastic: 'Plastic',
  plasticCard: 'Plastic Card',
  plasticCards: 'Plastic Cards',
  plasticCardDesc: 'Use this card for your in-store purchases.',
  plasticCardRequestSuccess: 'You have successfully requested a Plastic card',
  photoPermissionRequired: 'Photo permission required',
  purchaseLimit: 'Purchase limit',

  qrcodeValue: 'http://www.xpens.io',

  registerPin: 'Register PIN',
  registerPinDesc: 'Secure your account by nominating your 4-digit PIN',

  requested: 'Requested',
  requests: 'Requests',
  requestUpdates: 'Request updates',
  requestUpdatesDesc:
    'When the status of your request has changed, including your new messages.',
  requestApprovals: 'Request approvals',
  requestApprovalsDesc: 'When a member of your team creates a request',
  requestVirtualCard: 'Request Card',
  requestPlasticCard: 'Request Card',
  requestCard: 'Request Card',
  resendCode: 'Resend code',
  resendCodeDesc: "Didn't receive the code?",
  retake: 'Retake',
  rules: 'Rules',

  save: 'Save',

  scanDesc: 'Place the QR code inside the center guide.',
  scannerTitle: 'Scan to pair card',
  scannerDesc: 'Find and scan the QR code inside your card kit.',
  scanning: 'Scanning...',

  search: 'Search',
  searchPayment: 'Search payment',
  searchRequest: 'Search request',
  sent: 'Sent',
  sessionExpired: 'Session Expired',
  settings: 'Settings',
  selectDate: 'Select a date',
  signIn: 'Sign in',
  signInFailed: 'Sign in failed',
  signInFailedDesc:
    "We're unable to sign you in via Google. Make sure your google account tied to a registered Xpensio account",
  signInGoogle: 'Sign in with Google',
  signOut: 'Sign out',
  signOutMessage: 'Are you sure you want to sign out?',
  signUp: 'Sign up now',
  skipBiometrics: 'No, I prefer to use my password',
  state: 'State',
  status: 'Status',
  submit: 'Submit',
  summary: 'Summary',
  success: 'Success',

  tagline: 'TAGLINE HERE',
  tax: 'Tax',
  taxable: 'Taxable',
  team: 'Team',
  teams: 'Teams',
  tinNumber: 'TIN number',
  title: 'Title',
  to: 'To',
  total: 'Total',
  totalAmount: 'Total amount',
  type: 'Type',

  useFace: isAndroid ? 'Use face scanner' : 'Use Face ID',
  useFingerprint: isAndroid ? 'Use fingerprint' : 'Use Touch ID',
  uploadProfileImg: 'Upload profile image',
  unableToRequest: 'Unable to request',
  unableToUpload: 'Unable to upload',
  unableToDeny: 'Unable to deny',
  unableToApprove: 'Unable to approve',
  unableToUploadDescription: 'Failed to upload image',
  unlock: 'Unlock',

  value: 'Value',
  validThru: 'Valid Thru',
  virtual: 'Virtual',
  virtualCard: 'Virtual Card',
  virtualCards: 'Virtual Cards',
  virtualCardDesc:
    'Use this card for all  your online transactions and subscriptions.',
  virtualCardViewWarning: 'Do not share your card information to anyone',
  virtualCardRequestSuccess: 'You have successfully requested a Virtual Card',
  virtualCardReminder:
    'This card is issued by MatchMove Pay Pte Ltd pursuant to license by MasterCard Asia/Pacific Pte Ltd.',

  viewDetails: 'View Details',

  writeAMessage: 'Write a message...',

  yes: 'Yes',

  zipCode: 'ZIP code',
};

export default strings;
